[package]
name = "quota_tray_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
secrecy = { version = "0.10", features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
secrecy = { version = "0.10", features = ["serde"] }
time = { workspace = true }
